"""cc-ra: findings.json + context.json → REPORT-{date}.md.

`05_report.md` 의 템플릿 구조를 따른다. 페르소나 카운트, 카테고리 분포, 5분 요약,
finding 본문, Low Confidence 섹션, 통계까지 한 파일에 렌더.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path


CATEGORY_NAMES = {
    "A": "Temporal/Frame Ordering",
    "B": "Implicit Invariant Violation",
    "C": "State Coupling Gap",
    "D": "Event Leakage / Layering",
    "E": "Cache/Recompute Aggression",
    "F": "Architecture / Abstraction Leak",
    "G": "Domain-specific Hazard",
    "H": "Spec ↔ Implementation Drift",
}


def render(findings: list[dict], context: dict, *, threshold: float = 0.4) -> str:
    main = [f for f in findings if f.get("confidence", 1.0) >= threshold]
    low = [f for f in findings if f.get("confidence", 1.0) < threshold]
    main.sort(key=lambda f: -f.get("priority_score", 0.0))
    low.sort(key=lambda f: -f.get("priority_score", 0.0))

    workspace = context.get("workspace", "?")
    files = context.get("files", [])
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    out = []
    out.append(f"# cc-ra REPORT — {Path(workspace).name} ({date})\n")
    out.append(f"> Generated by cc-ra v0.1\n> Workspace: `{workspace}`\n> Files analyzed: {len(files)} (.rs)\n")

    # priority bins
    bins = Counter()
    for f in main:
        s = f.get("priority_score", 0.0)
        if s >= 0.5:
            bins["critical"] += 1
        elif s >= 0.3:
            bins["high"] += 1
        elif s >= 0.1:
            bins["medium"] += 1
        else:
            bins["low"] += 1

    out.append(
        f"> Findings: **{bins['critical']} critical**, "
        f"{bins['high']} high, {bins['medium']} medium, {bins['low']} low "
        f"(+ {len(low)} low-confidence)\n"
    )

    # ───────── 5-분 요약 ─────────
    out.append("\n---\n\n## 5-분 요약\n")
    critical = [f for f in main if f.get("priority_score", 0) >= 0.5][:5]
    if not critical:
        out.append("\n🟢 Critical 발견 없음 (priority_score ≥ 0.5).\n")
    else:
        for i, f in enumerate(critical, 1):
            title = f.get("title") or f.get("claim", "")[:80]
            loc = f.get("location", "?")
            scen = f.get("scenario", "").splitlines()[0][:120] if f.get("scenario") else ""
            out.append(f"\n{i}. **[{f['id']}]** {title} — `{loc}`\n   {scen}\n")

    # ───────── 페르소나 ─────────
    out.append("\n---\n\n## 페르소나별 발견 요약\n\n")
    persona_counts = defaultdict(int)
    persona_unique = defaultdict(int)
    persona_top_cat = defaultdict(Counter)
    for f in main:
        for p in f.get("personas", []):
            persona_counts[p] += 1
            persona_top_cat[p][f.get("category", "?")] += 1
        if len(f.get("personas", [])) == 1:
            persona_unique[f["personas"][0]] += 1

    out.append("| Persona | Findings | Unique | Top Category |\n")
    out.append("|---------|---------:|-------:|--------------|\n")
    for p in sorted(persona_counts, key=lambda x: -persona_counts[x]):
        top_cat = persona_top_cat[p].most_common(1)[0][0] if persona_top_cat[p] else "—"
        out.append(f"| {p} | {persona_counts[p]} | {persona_unique[p]} | {top_cat} |\n")
    out.append(f"| **TOTAL (after triage)** | {len(main)} | — | — |\n")

    # ───────── 카테고리 ─────────
    out.append("\n---\n\n## 카테고리 분포\n\n")
    cat_counts = Counter(f.get("category", "?") for f in main)
    out.append("| Code | Category | Count |\n|------|----------|------:|\n")
    for code in "ABCDEFGH":
        out.append(f"| {code} | {CATEGORY_NAMES.get(code,'?')} | {cat_counts.get(code,0)} |\n")

    # ───────── Findings ─────────
    out.append("\n---\n\n## Findings (Priority 순)\n")
    for f in main:
        out.append("\n" + render_finding(f))

    # Low confidence
    if low:
        out.append("\n---\n\n## Low Confidence Findings\n\n")
        out.append("> confidence < {:.1f} — 추가 검증 필요.\n".format(threshold))
        for f in low:
            out.append("\n" + render_finding(f))

    # Stats
    out.append("\n---\n\n## Statistics & Provenance\n\n```yaml\n")
    out.append(f"date: {date}\n")
    out.append(f"main_findings: {len(main)}\n")
    out.append(f"low_confidence: {len(low)}\n")
    out.append(f"by_priority:\n")
    for k in ("critical", "high", "medium", "low"):
        out.append(f"  {k}: {bins[k]}\n")
    out.append(f"by_category:\n")
    for code in "ABCDEFGH":
        out.append(f"  {code}: {cat_counts.get(code, 0)}\n")
    out.append(f"files_analyzed: {len(files)}\n")
    out.append("```\n")

    return "".join(out)


def render_finding(f: dict) -> str:
    title = f.get("title") or f.get("claim", "")[:80]
    cat = f.get("category", "?")
    cat_name = CATEGORY_NAMES.get(cat, "?")
    out = []
    out.append(f"### {f['id']} · [{cat} · {cat_name}] {title}\n\n")
    out.append(f"- **Location**: `{f.get('location','?')}`\n")
    personas = f.get("personas", [])
    pc_marker = " (concur)" if f.get("personas_concur") else ""
    out.append(f"- **Personas**: {', '.join(personas)}{pc_marker}\n")
    out.append(
        f"- **Severity**: {f.get('severity',0):.2f} · "
        f"**Likelihood**: {f.get('likelihood',0):.2f} · "
        f"**Blast**: {f.get('blast_radius',0):.2f} · "
        f"**Confidence**: {f.get('confidence',0):.2f}\n"
    )
    out.append(f"- **Priority Score**: {f.get('priority_score',0):.3f}\n\n")

    if claim := f.get("claim"):
        out.append(f"**Claim** — {claim}\n\n")
    if scenario := f.get("scenario"):
        out.append(f"**Scenario**:\n\n{scenario}\n\n")
    if evidence := f.get("evidence"):
        out.append("**Evidence**:\n\n")
        for ev in evidence:
            out.append(f"- {ev}\n")
        out.append("\n")
    if root := f.get("root_cause"):
        out.append(f"**Root Cause**:\n\n{root}\n\n")
    if fix := f.get("suggested_fix"):
        out.append(f"**Suggested Fix**:\n\n{fix}\n\n")
    out.append("---\n")
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--findings", required=True, type=Path)
    ap.add_argument("--context", required=True, type=Path)
    ap.add_argument("--output", required=True, type=Path)
    ap.add_argument("--threshold", type=float, default=0.4)
    args = ap.parse_args()

    findings = json.loads(args.findings.read_text(encoding="utf-8"))
    context = json.loads(args.context.read_text(encoding="utf-8"))
    md = render(findings, context, threshold=args.threshold)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(md, encoding="utf-8")
    print(f"[render_report] {len(findings)} findings → {args.output} ({len(md)} chars)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
